version: "3.12.1"

services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:password@flask_db:5432/postgres
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
